### PR TITLE
Clean up the Code and Tuning the UI

### PR DESCRIPTION
**Pull request by Muhammad-Yazdian**
This pull request addresses the following issues:

1. Style and naming convention are fixed.
2. The user interface was tuned to prevent text jumps and to provide information more clearly.

### CODE REVIEW

**Comment by FidalMathew** [comment]
@Muhammad-Yazdian could you deploy this branch on Github pages and send me the link. 
It will be easier for me to review it.

**Comment by Muhammad-Yazdian** [comment]
@FidalMathew Here are the [file changes](https://github.com/FidalMathew/ROLL-THE-DICE/pull/10/files).

**Comment by FidalMathew** [comment]
> @FidalMathew Here are the [file changes](https://github.com/FidalMathew/ROLL-THE-DICE/pull/10/files).

I can see this, could you send the screenshot of the UI you have made?

**Comment by Muhammad-Yazdian** [comment]
[I just updated the screenshots in the README file.](https://github.com/Muhammad-Yazdian/ROLL-THE-DICE#readme)

**Comment by FidalMathew** [comment]
@Muhammad-Yazdian could you also send the desktop view. You can take a screen snippet and paste it here in the comments.

**Comment by Muhammad-Yazdian** [comment]
Here is the desktop view. As you can see the numbers are not perfectly aligned compared to the mobile view


screenshot_desktop

Mobile view
screenshot_phone
:

**Comment by FidalMathew** [comment]
image
@Muhammad-Yazdian  Don't you think the previous UI was better? It was more symmetrical

**Comment by Muhammad-Yazdian** [comment]
If you zoom out you can see the issue still persists. I just recreated the issue for the previous UI (see below). 

Recreated

Also here is screenshot of my PR at a different zoom level.
image

For initial development stage, size compatibility handling will pop up for every single feature added/removed. So I suggest that to handle size compactivity issues at the end of the UI design. We we confirmed the whole features. I just initiated the issue so that we don't forgot it.

**Comment by FidalMathew** [comment]
@Muhammad-Yazdian Thank you for the contribution :)

**Comment by Muhammad-Yazdian** [comment]
@FidalMathew Thank you.

**Pull request merged**
