### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Sujansinhthakor**
Made few changes in Styling of game

### CODE REVIEW

**Comment by FidalMathew** [comment]
@Sujansinh-thakor could send the screenshot of the current page?

**Comment by Sujansinhthakor** [comment]
> @Sujansinh-thakor could send the screenshot of the current page?
here is the link of screenshot  https://ibb.co/GsJRy11

**Comment by FidalMathew** [comment]
@Sujansinh-thakor I feel there's no actual color combination going on here, it's looking scattered. The previous one was better I feel.

**Comment by Sujansinhthakor** [comment]
> @Sujansinh-thakor I feel there's no actual color combination going on here, it's looking scattered. The previous one was better I feel.

Ok 👍

**Comment by FidalMathew** [comment]
@Sujansinh-thakor, if you'd want to contribute in some manner, I would suggest, you could add better dice pictures compared to that of now.
Do, confirm with me before working on it. Don't let your effort go to waste :)

**Comment by Sujansinhthakor** [comment]
Ok

**Pull request closed without merging**
